package exception_handling;

public class exception {

	public static void main(String args[])
	{
		try
		{
			int a[] = {1,2,5,7};
			System.out.println(a[9]);
		}
		
		catch(Exception e)
		{
			System.out.println("there is run time erropr in your code!!");
		}
		
		
//		int a[]= {1,4,6,9};
//		System.out.println(a[8]);
		
		
		
		
		
		
		
		
	}

}